mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
routing-mark: 7894
allow-lan: true
ipv6: false
mode: rule
unified-delay: true
tcp-concurrent: true
find-process-mode: off
log-level: info
geodata-loader: standard
external-controller: :9999
disable-keep-alive: false
profile:
  store-selected: true
proxy-groups:
  - name: 节点选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies: &a1
      - 落地节点
      - 手动切换
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
      - 故障转移
      - DIRECT
  - name: 落地节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Airport.png
    type: select
    include-all: true
    filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地
  - name: 前置代理
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Area.png
    type: select
    include-all: true
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地
    proxies: *a1
  - name: 手动切换
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
    type: fallback
    url: https://cp.cloudflare.com/generate_204
    proxies:
      - 落地节点
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
    interval: 180
    tolerance: 20
    lazy: false
  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    include-all: true
    proxies: &a2
      - 节点选择
      - 落地节点
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
      - 手动切换
      - 全球直连
  - name: 人工智能
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies: *a2
  - name: 加密货币
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cryptocurrency_3.png
    type: select
    proxies: *a2
  - name: PayPal
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/PayPal.png
    type: select
    proxies: *a2
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies: *a2
  - name: Microsoft
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    type: select
    proxies: *a2
  - name: Apple
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple_2.png
    type: select
    proxies: *a2
  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies: *a2
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies: *a2
  - name: Netflix
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies: *a2
  - name: Spotify
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    type: select
    proxies: *a2
  - name: TikTok
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    type: select
    proxies: *a2
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies: *a2
  - name: PikPak
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/PikPak.png
    type: select
    proxies: *a2
  - name: 巴哈姆特
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bahamut.png
    type: select
    proxies:
      - 台湾节点
      - 节点选择
      - 手动切换
      - 全球直连
  - name: 哔哩哔哩
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies:
      - 全球直连
      - 台湾节点
      - 香港节点
  - name: Twitter(X)
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    type: select
    proxies: *a2
  - name: 新浪微博
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Weibo.png
    type: select
    include-all: true
    proxies:
      - 全球直连
      - 节点选择
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
      - 手动切换
  - name: Truth Social
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/TruthSocial.png
    type: select
    proxies:
      - 美国节点
      - 节点选择
      - 手动切换
  - name: 学术资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Scholar.png
    type: select
    proxies:
      - 节点选择
      - 手动切换
      - 全球直连
  - name: 开发者资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    type: select
    proxies: *a2
  - name: 瑟琴网站
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub.png
    type: select
    proxies: *a2
  - name: 游戏平台
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies: *a2
  - name: 测速服务
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png
    type: select
    proxies: *a2
  - name: FCM推送
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 全球直连
      - Google
      - 节点选择
  - name: SSH(22端口)
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Server.png
    type: select
    proxies: *a2
  - name: Steam修复
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    type: select
    proxies:
      - 全球直连
      - 游戏平台
      - 节点选择
  - name: Play商店修复
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/GooglePlay.png
    type: select
    proxies:
      - 全球直连
      - Google
      - 节点选择
  - name: 搜狗输入
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Sougou.png
    type: select
    proxies:
      - 全球直连
      - REJECT
  - name: 全球直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - 全球直连
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)香港|港|HK|hk|Hong Kong|HongKong|hongkong
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 澳门节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Macao.png
    include-all: true
    filter: (?i)澳门|MO|Macau
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美国|美|US|United States
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 英国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_Kingdom.png
    include-all: true
    filter: (?i)英国|United Kingdom|UK|伦敦|London
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 韩国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png
    include-all: true
    filter: (?i)KR|Korea|KOR|首尔|韩|韓
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 新加坡节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 德国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Germany.png
    include-all: true
    filter: (?i)德国|德|DE|Germany
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 法国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/France.png
    include-all: true
    filter: (?i)法国|法|FR|France
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: 加拿大节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Canada.png
    include-all: true
    filter: (?i)加拿大|Canada|CA
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: load-balance
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - 节点选择
      - 落地节点
      - 前置代理
      - 手动切换
      - 故障转移
      - 静态资源
      - 人工智能
      - 加密货币
      - PayPal
      - Telegram
      - Microsoft
      - Apple
      - Google
      - YouTube
      - Netflix
      - Spotify
      - TikTok
      - E-Hentai
      - PikPak
      - 巴哈姆特
      - 哔哩哔哩
      - Twitter(X)
      - 新浪微博
      - Truth Social
      - 学术资源
      - 开发者资源
      - 瑟琴网站
      - 游戏平台
      - 测速服务
      - FCM推送
      - SSH(22端口)
      - Steam修复
      - Play商店修复
      - 搜狗输入
      - 全球直连
      - 广告拦截
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://adrules.top/adrules_domainset.txt
    path: ./ruleset/ADBlock.txt
  TruthSocial:
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TruthSocial.list
    path: ./ruleset/TruthSocial.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SogouInput:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.txt
  StaticResources:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./ruleset/StaticResources.txt
  CDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./ruleset/CDNResources.txt
  AI:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./ruleset/AI.txt
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TikTok.list
    path: ./ruleset/TikTok.list
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  PlayStoreFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/GooglePlayStoreFix.list
    path: ./ruleset/GooglePlayStoreFix.list
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list
  GoogleFCM:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./ruleset/FirebaseCloudMessaging.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list
  Weibo:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/Weibo.list
    path: ./ruleset/Weibo.list
  AdditionalCDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalCDNResources.list
    path: ./ruleset/AdditionalCDNResources.list
  SpeedTest:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/speedtest.txt
    path: ./ruleset/SpeedTest.list
rules:
  - RULE-SET,ADBlock,广告拦截
  - RULE-SET,AdditionalFilter,广告拦截
  - RULE-SET,SogouInput,搜狗输入
  - RULE-SET,TruthSocial,Truth Social
  - RULE-SET,StaticResources,静态资源
  - RULE-SET,CDNResources,静态资源
  - RULE-SET,AdditionalCDNResources,静态资源
  - RULE-SET,AI,人工智能
  - RULE-SET,EHentai,E-Hentai
  - RULE-SET,TikTok,TikTok
  - RULE-SET,SteamFix,Steam修复
  - RULE-SET,PlayStoreFix,Play商店修复
  - RULE-SET,GoogleFCM,FCM推送
  - RULE-SET,Weibo,新浪微博
  - RULE-SET,SpeedTest,测速服务
  - GEOSITE,PAYPAL@CN,全球直连
  - GEOSITE,PAYPAL,PayPal
  - GEOSITE,GOOGLE-PLAY@CN,全球直连
  - GEOSITE,APPLE@CN,全球直连
  - GEOSITE,APPLE,Apple
  - GEOSITE,TELEGRAM,Telegram
  - GEOSITE,YOUTUBE@CN,全球直连
  - GEOSITE,YOUTUBE,YouTube
  - GEOSITE,GOOGLE,Google
  - GEOSITE,NETFLIX,Netflix
  - GEOSITE,SPOTIFY,Spotify
  - GEOSITE,TWITTER,Twitter(X)
  - GEOSITE,BAHAMUT,巴哈姆特
  - GEOSITE,BILIBILI,哔哩哔哩
  - GEOSITE,CATEGORY-DEV,开发者资源
  - GEOSITE,CATEGORY-PORN,瑟琴网站
  - GEOSITE,CATEGORY-GAMES@CN,全球直连
  - GEOSITE,CATEGORY-GAMES,游戏平台
  - GEOSITE,CATEGORY-SCHOLAR-!CN,学术资源
  - GEOSITE,CATEGORY-SCHOLAR-CN,全球直连
  - GEOSITE,CATEGORY-CRYPTOCURRENCY,加密货币
  - GEOSITE,MICROSOFT@CN,全球直连
  - GEOSITE,MICROSOFT,Microsoft
  - GEOSITE,PIKPAK,PikPak
  - GEOSITE,CN,全球直连
  - GEOSITE,PRIVATE,全球直连
  - GEOIP,NETFLIX,Netflix,no-resolve
  - GEOIP,GOOGLE,Google,no-resolve
  - GEOIP,TELEGRAM,Telegram,no-resolve
  - GEOIP,CN,全球直连,no-resolve
  - GEOIP,LAN,全球直连,no-resolve
  - GEOIP,PRIVATE,全球直连,no-resolve
  - DST-PORT,22,SSH(22端口)
  - MATCH,节点选择
sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
      override-destination: true
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
      override-destination: false
    QUIC:
      ports:
        - 443
        - 8443
      override-destination: true
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - system
    - quic://223.5.5.5
    - tls://dot.pub
    - tls://dns.alidns.com
  fallback:
    - quic://dns0.eu
    - https://dns.cloudflare.com/dns-query
    - https://dns.sb/dns-query
    - tcp://208.67.222.222
    - tcp://8.26.56.2
  proxy-server-nameserver:
    - quic://223.5.5.5
    - tls://dot.pub
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb

